#define PipeUD 11	//直的
#define PipeRL 12	//橫的
#define PipeLU 13	//左上
#define PipeLD 14	//左下
#define PipeRU 15	//右上
#define PipeRD 16	//右下
#define P_straight 6	//行列方陣數
#define Pipe_W 32	//水管寬
#define Pipe_H 32	//水管高
#define Pipe_Start 2	//水管入口
#define Pipe_End 3	//水管出口
#define Pipe_OVER 100	//通路
#define Pipe_chack 5	//水管突變遮罩
#define Pipe_mutation0 0	//水管突變變數0：當水管突變機率不變時(跟鄰近接通)
#define Pipe_mutation1 1	//水管突變變數1：當水管突變機率變大時(跟鄰近不通)
#define Pipe_mutation2 2	//水管突變變數2：當水管為末端時
#define Pipe_mutation3 1	//水管突變變數2：當水管為末端周圍時
